apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: roboshop
data:
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels: # these labels are deployment labels
    app: redis
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: redis
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: redis
        project: roboshop
        tier: app
    spec:
      containers:
      - name: redis
        image: jaga143/redis:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379 #container-port